### ISSUE TITLE
Make database name for hash_md5() UDF configurable

### ISSUE THREAD

**Issue by adamtwo** [Teradata/dbt-teradata-utils#2]
### Describe the feature
`teradata__hash` macro calls `GLOBAL_FUNCTIONS.hash_md5()` function. It's very common for Teradata users to install this UDF. Many customers have installed it in databases that are not called `GLOBAL_FUNCTIONS`. To make this macro work, they will have to install `hash_md5()` again. 

This feature request is to make `teradata__hash` configurable, so that users can define the name of the database that contains `hash_md5()` function.

### Describe alternatives you've considered
Install `hash_md5()` again in `GLOBAL_FUNCTIONS` database.

### Additional context
N/A

### Who will this benefit?
Users who rely on `hash_md5()` directly or on other macros that depend on `hash_md5()`.

**Comment by septimit** [comment]
Hi Adam,
I know I'm late to the party, but I think there is a simple way to implement this using [dbt project variables](https://docs.getdbt.com/docs/build/project-variables).
Suppose we define a variable in dbt_project.yml:

```
name: my_dbt_project
version: 1.0.0
config-version: 2
vars:
   # The custom hash_md5 function
   teradata_hash_md5: 'FUNCTIONS.hash_md5'
 
 models:
     ...
```

This could be used in the [hash.sql](https://github.com/Teradata/dbt-teradata/blob/main/dbt/include/teradata/macros/utils/hash.sql) 

```
{% macro teradata__hash(field) -%}
    {%- set hash_md5 = var('teradata_hash_md5', 'GLOBAL_FUNCTIONS.hash_md5') -%}
    {{ hash_md5 }}(cast({{field}} AS {{type_string()}}))
{%- endmacro %}
```
